log_path:
  dev: ./log/info_{hostname}.log
  stg: /mnt/pvc/pvc-ph-irisk-id9743-vol723550-stg/log/hf_4p4/info_{hostname}.log
  pro: /mnt/pvc/pvc-ph-ai-model-id10065746-vol923966-prd/szr/log/hf_4p4/info_{hostname}.log
