log_path:
  dev: ./log/info_{hostname}.log
  stg: /mnt/pvc/pvc-ph-irisk-id9743-vol723550-stg/log/hf_xy/info_{hostname}.log
  pro: /mnt/pvc/pvc-ph-ai-model-id10065746-vol923966-prd/szr/log/hf_xy/info_{hostname}.log

dark_bg:
  model_threshold: 0.95
  dark_pixel_thresh: 30
  dark_ratio_thresh: 0.90
  bright_thresh: 60
  min_patch_area: 500
  patch_ratio_thresh: 0.02
  spot_ratio_thresh: 0.10
  bbox_expand_ratio: 0.0
  bbox_expand_up_ratio: 0.1
